# Generated by Django 5.0.7 on 2025-02-12 09:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Link')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('views', models.IntegerField(default=0, verbose_name='Number of views')),
                ('article_notes', models.TextField(blank=True, verbose_name='note')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article(s)',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
