# Generated by Django 5.0.7 on 2025-03-15 10:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_eng',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content_eng'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_eng',
            field=models.CharField(default=True, max_length=255, verbose_name='Name_eng'),
        ),
    ]
