# Generated by Django 5.0.7 on 2025-03-15 10:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineencyclopedia',
            name='definition',
            field=tinymce.models.HTMLField(),
        ),
    ]
