# Generated by Django 5.0.7 on 2024-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_gsmpmember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmpmember',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
