# Generated by Django 5.0.7 on 2024-12-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_gsmpmember_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmpmember',
            old_name='is_email_verified',
            new_name='email_verified',
        ),
    ]
