# Generated by Django 5.0.7 on 2024-12-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_is_email_verified_gsmpmember_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmpmember',
            old_name='email_verified',
            new_name='email_confirmed',
        ),
    ]
