# Generated by Django 5.0.7 on 2024-12-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_email_verified_gsmpmember_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmpmember',
            name='Gender',
            field=models.TextField(blank=True, choices=[('მამრობითი', 'მამრ'), ('მდედრობითი', 'მდედრ')], verbose_name='სქესი'),
        ),
    ]
