# Generated by Django 5.0.7 on 2025-01-22 12:10

import django.utils.timezone
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_gsmpmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmpmember',
            name='Country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
