# Generated by Django 5.0.7 on 2025-01-22 12:27

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_gsmpmember_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
