# Generated by Django 5.0.7 on 2025-01-22 14:50

import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_gsmpmember_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsmpmember',
            name='Country',
        ),
        migrations.AddField(
            model_name='gsmpmember',
            name='academic_degree',
            field=models.TextField(blank=True, choices=[('ბაკალავრი', 'ბაკალავრი'), ('მაგისტრი', 'მაგისტრი')], verbose_name='აკადემიური ხარისხი'),
        ),
        migrations.AddField(
            model_name='gsmpmember',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='მისამართი'),
        ),
        migrations.AddField(
            model_name='gsmpmember',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ქალაქი'),
        ),
        migrations.AddField(
            model_name='gsmpmember',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='საფოსტო ინდექსი'),
        ),
        migrations.AddField(
            model_name='gsmpmember',
            name='workplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='სამუშაო ადგილი'),
        ),
        migrations.AddField(
            model_name='gsmpmember',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
