# Generated by Django 5.0.7 on 2025-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_gsmpmember_country_gsmpmember_academic_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmpmember',
            name='academic_position',
            field=models.TextField(blank=True, choices=[('ასისტენტ პროფესორი', 'ასისტ. პროფ.'), ('ასოცირებული პროფესორი', 'ასოც. პროფ.'), ('პროფესორი', 'პროფ.')], verbose_name='აკადემიური პოზიცია'),
        ),
    ]
