# Generated by Django 5.0.7 on 2025-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_gsmpmember_workplace_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('სხვა', 'სხვა'), ('ადმინისტრაციული', 'ადმინისტრაციული'), ('საგანმანათლებო', 'საგანმანათლებო'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('კვლევა', 'კვლევა')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
