# Generated by Django 5.0.7 on 2025-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_gsmpmember_workplace_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='academic_position',
            field=models.TextField(blank=True, choices=[('ასისტენტ პროფესორი', 'ასისტ. პროფ.'), ('ასოცირებული პროფესორი', 'ასოც. პროფ.'), ('პროფესორი', 'პროფესორი')], verbose_name='აკადემიური პოზიცია'),
        ),
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კვლევა', 'კვლევა'), ('სხვა', 'სხვა'), ('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('საგანმანათლებო', 'საგანმანათლებო'), ('ადმინისტრაციული', 'ადმინისტრაციული'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
