# Generated by Django 5.0.7 on 2025-01-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_gsmpmember_workplace_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('სხვა', 'სხვა'), ('ადმინისტრაციული', 'ადმინისტრაციული'), ('კვლევა', 'კვლევა'), ('საგანმანათლებო', 'საგანმანათლებო'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
