# Generated by Django 5.0.7 on 2025-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_gsmpmember_workplace_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('კვლევა', 'კვლევა'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები'), ('საგანმანათლებო', 'საგანმანათლებო'), ('სხვა', 'სხვა'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('ადმინისტრაციული', 'ადმინისტრაციული')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
