# Generated by Django 5.0.7 on 2025-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_gsmpmember_workplace_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კვლევა', 'კვლევა'), ('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('საგანმანათლებო', 'საგანმანათლებო'), ('სხვა', 'სხვა'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები'), ('ადმინისტრაციული', 'ადმინისტრაციული'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
