# Generated by Django 5.0.7 on 2025-02-08 15:22

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_gsmpmember_workplace_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('სხვა', 'სხვა'), ('კვლევა', 'კვლევა'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('ადმინისტრაციული', 'ადმინისტრაციული'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები'), ('საგანმანათლებო', 'საგანმანათლებო')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
