# Generated by Django 5.0.7 on 2025-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_alter_gsmpmember_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კვლევა', 'კვლევა'), ('საგანმანათლებო', 'საგანმანათლებო'), ('სხვა', 'სხვა'), ('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები'), ('ადმინისტრაციული', 'ადმინისტრაციული')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
