# Generated by Django 5.0.7 on 2025-02-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_alter_gsmpmember_email_alter_gsmpmember_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='academic_degree',
            field=models.TextField(blank=True, choices=[('ბაკალავრი', 'ბაკალავრი'), ('მაგისტრი', 'მაგისტრი'), ('მეცნიერებათა დოქტორი', 'მეცნიერებათა დოქტორი')], verbose_name='აკადემიური ხარისხი'),
        ),
        migrations.AlterField(
            model_name='gsmpmember',
            name='academic_position',
            field=models.TextField(blank=True, choices=[('ასისტენტი', 'ასისტენტი'), ('ასისტენტ პროფესორი', 'ასისტ. პროფ.'), ('ასოცირებული პროფესორი', 'ასოც. პროფ.'), ('პროფესორი', 'პროფესორი'), ('პროფესორი-ემერიტუსი', 'პროფესორი-ემერიტუსი')], verbose_name='აკადემიური პოზიცია'),
        ),
        migrations.AlterField(
            model_name='gsmpmember',
            name='workplace_activity',
            field=models.TextField(blank=True, choices=[('კლინიკური/სამედიცინო სერვისი', 'კლინიკური/სამედიცინო სერვისი'), ('კვლევა', 'კვლევა'), ('ორივე - კლინიკური/კვლევითი', 'ორივე - კლინიკური/კვლევითი'), ('ადმინისტრაციული', 'ადმინისტრაციული'), ('ფინანსები, მარკეტინგი, გაყიდვები', 'ფინანსები, მარკეტინგი, გაყიდვები'), ('საგანმანათლებო', 'საგანმანათლებო'), ('სხვა', 'სხვა')], verbose_name='სამუშაო აქტიობა'),
        ),
    ]
