# Generated by Django 5.0.7 on 2025-02-08 17:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_alter_gsmpmember_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmpmember',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
